version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
    groups:
      tauri:
        patterns:
          - "@tauri-apps/*"
      lingui:
        patterns:
          - "@lingui/*"
      tanstack:
        patterns:
          - "@tanstack/*"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      tauri:
        patterns:
          - "tauri*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
