use serde::{Deserialize, Serialize};
use specta::Type;

// Keep wire names and diagnostics together so adding a code cannot omit either.
macro_rules! custom_codes {
    ($($variant:ident => ($code:literal, $message:literal)),* $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
        pub enum CustomErrorCode {
            $(#[serde(rename = $code)] $variant),*
        }

        impl CustomErrorCode {
            pub fn as_str(self) -> &'static str {
                match self { $(Self::$variant => $code),* }
            }

            pub fn message(self) -> &'static str {
                match self { $(Self::$variant => $message),* }
            }
        }
    };
}

custom_codes! {
    AppShuttingDown => ("app:shutting_down", "Application is shutting down"),
    AppMaintenanceInProgress => ("app:maintenance_in_progress", "Application data maintenance is in progress"),
    AppOperationsBusy => ("app:operations_busy", "Execution pipeline did not become idle before maintenance deadline"),
    AppDataBusy => ("app:data_busy", "Data cleanup blocked by a running domain task"),
    AppDataModuleSeparateStore => ("app:data_module_separate_store", "Data module is stored outside the main database"),
    AppDataNotJson => ("appdata:not_json", "Import file is not valid JSON"),
    AppDataNotMftpFile => ("appdata:not_mftp_file", "File is not an mftp export file"),
    AppDataFormatInvalid => ("appdata:format_invalid", "Export file is missing a required field or has an invalid value"),
    AppDataKdfUnsupported => ("appdata:kdf_unsupported", "Export file uses an unsupported key derivation algorithm"),
    AppDataCipherUnsupported => ("appdata:cipher_unsupported", "Export file uses an unsupported cipher"),
    AppDataDecryptFailed => ("appdata:decrypt_failed", "Wrong password or corrupted export file"),
    AppDataPasswordRequired => ("appdata:password_required", "Password is required for the encrypted export file"),
    AppDataNoSections => ("appdata:no_sections", "Export file has no data sections"),
    AppDataSectionInvalid => ("appdata:section_invalid", "Export data section is invalid"),
    VaultEntryNotFound => ("vault:entry_not_found", "Vault entry not found"),
    HostNotFound => ("hosts:host_not_found", "Host not found"),
    HostAuthTypeInvalid => ("hosts:auth_type_invalid", "Stored host authentication type is invalid"),
    KeyNotFound => ("keys:key_not_found", "SSH key not found"),
    TodoTitleRequired => ("todo:title_required", "Todo title is required"),
    TodoDueTimeInvalid => ("todo:due_time_invalid", "Todo due timestamp is outside the supported range"),
    TodoDueDateInvalid => ("todo:due_date_invalid", "Todo due date must use YYYY-MM-DD"),
    TodoItemNotFound => ("todo:item_not_found", "Todo item not found"),
    RoomAddressInvalid => ("room:address_invalid", "Invalid game room address"),
    RoomHandshakeInvalid => ("room:handshake_invalid", "Unexpected game room handshake response"),
    RoomCodeInvalid => ("room:code_invalid", "Game room code is incorrect"),
    RoomFull => ("room:full", "Game room is full"),
    RoomGameMismatch => ("room:game_mismatch", "Game room uses a different game"),
    RoomJoinRejected => ("room:join_rejected", "Game room rejected the join request"),
    RoomNotJoined => ("room:not_joined", "Not currently in a game room"),
    RoomPeerMissing => ("room:peer_missing", "Game room peer is not connected"),
    RoomFrameTooLarge => ("room:frame_too_large", "Game room frame exceeds the size limit"),
    LanTransferCancelled => ("lan:transfer_cancelled", "LAN transfer was cancelled"),
    LanTransferIncomplete => ("lan:transfer_incomplete", "LAN transfer worker ended before completion"),
    LanTransferLimitReached => ("lan:transfer_limit_reached", "LAN concurrent transfer limit reached"),
    LanRequestInvalid => ("lan:request_invalid", "Invalid or incomplete LAN HTTP request"),
    LanRequestHeadersTooLarge => ("lan:request_headers_too_large", "LAN HTTP headers exceed the size limit"),
    LanUploadInvalid => ("lan:upload_invalid", "Invalid upload length, range or conflict mode"),
    LanUploadNameInvalid => ("lan:upload_name_invalid", "Invalid upload relative path"),
    LanUploadOffsetMismatch => ("lan:upload_offset_mismatch", "Upload offset does not match the destination size"),
    LanUploadTargetBusy => ("lan:upload_target_busy", "Upload destination is in use"),
    LanUploadTargetInvalid => ("lan:upload_target_invalid", "Upload destination is not a regular file or directory"),
    LanUploadSpaceInsufficient => ("lan:upload_space_insufficient", "Insufficient disk space for the upload"),
    LanShareUnknown => ("lan:share_unknown", "Unknown or missing LAN share id"),
    LanSharedPathInvalid => ("lan:shared_path_invalid", "Requested path is invalid or escapes the shared directory"),
    LanSharedDirUnavailable => ("lan:shared_dir_unavailable", "Shared directory does not exist or cannot be accessed"),
    LanIpInvalid => ("lan:ip_invalid", "IP address is invalid"),
    LanBindIpNotLan => ("lan:bind_ip_not_lan", "Bind IP is not a LAN address"),
    LanBindPortUnavailable => ("lan:bind_port_unavailable", "No listening port is available in the requested range"),
    BtFileNotInTask => ("bt:file_not_in_task", "File does not belong to this download task"),
    BtTaskNotFound => ("bt:task_not_found", "Download task not found"),
    BtFileNotFound => ("bt:file_not_found", "Download file not found"),
    BtPreviewUnavailable => ("bt:preview_unavailable", "BT preview server is unavailable"),
    BtInvalidInfoHash => ("bt:invalid_info_hash", "Invalid torrent info hash"),
    BtTaskCancelled => ("bt:task_cancelled", "BT task was cancelled"),
    BtNoExportableFiles => ("bt:no_exportable_files", "Task has no files available for export"),
    BtInvalidArchivePath => ("bt:invalid_archive_path", "Archive path has no file name"),
    BtArchiveAlreadyExists => ("bt:archive_already_exists", "Archive destination already exists"),
    BtSessionRestoreFailed => ("bt:session_restore_failed", "Download session could not be restored"),
    BtTaskSizeOutOfRange => ("bt:task_size_out_of_range", "BT task size exceeds the database range"),
    BtExportNotCompleted => ("bt:export_not_completed", "Task is not completed yet, cannot export"),
    BtExportAlreadyDone => ("bt:export_already_done", "Task has already been exported"),
    BtSelectionEmpty => ("bt:selection_empty", "At least one file must be selected"),
    BtSelectionDuplicate => ("bt:selection_duplicate", "File selection contains duplicates"),
    BtSelectionInvalid => ("bt:selection_invalid", "File selection contains invalid or padding files"),
    BtHashMismatch => ("bt:hash_mismatch", "Resource id does not match the resolved torrent"),
    BtFinalizeCancelTimeout => ("bt:finalize_cancel_timeout", "Packaging job did not stop before the deadline"),
    BtReaddCompleted => ("bt:readd_completed", "Resource already downloaded; remove the existing task first"),
    BtReaddPackaging => ("bt:readd_packaging", "Resource is being processed, cannot add again"),
    BtReaddActiveSelection => ("bt:readd_active_selection", "Active task exists, cannot overwrite with a new file selection"),
    BtReaddConflict => ("bt:readd_conflict", "Resource already has a task, cannot add again"),
    BtTaskNotInitialized => ("bt:task_not_initialized", "BT task is missing or not initialized in the engine"),
    BtTaskCompletedNoCancel => ("bt:task_completed_no_cancel", "Completed task cannot be cancelled"),
    BtTaskNotRunning => ("bt:task_not_running", "BT task is not running"),
    BtStagingDirForeign => ("bt:staging_dir_foreign", "Refused to clean a directory not owned by BT"),
    BtInfoNotReady => ("bt:info_not_ready", "Torrent metadata is not ready; parse the source first"),
    BtNoDownloadableFiles => ("bt:no_downloadable_files", "Torrent has no downloadable files"),
    BtSourceUnsupported => ("bt:source_unsupported", "Only magnet links or .torrent file paths are supported"),
    BtProbeTimeout => ("bt:probe_timeout", "Fetching resource metadata timed out"),
    BtProbeUnexpected => ("bt:probe_unexpected", "Unexpected engine response: probe listed-only added torrent"),
    SshSessionNotFound => ("ssh:session_not_found", "SSH session is not registered"),
    SshShellNotOpen => ("ssh:shell_not_open", "SSH shell is not open"),
    SshShellClosed => ("ssh:shell_closed", "SSH shell is closed"),
    SshKeyNotSelected => ("ssh:key_not_selected", "Host has no authentication key selected"),
    SshInvalidWritePayload => ("ssh:invalid_write_payload", "Invalid terminal write payload"),
    SshNoAuthMethod => ("ssh:no_auth_method", "No SSH agent or local identity is available"),
    SshUsernameUnavailable => ("ssh:username_unavailable", "Local username is unavailable"),
    SftpTransferNotFound => ("sftp:transfer_not_found", "Transfer has not started or has finished"),
    SftpTransferNotPausable => ("sftp:transfer_not_pausable", "Current transfer phase cannot be paused"),
    SftpTransferCancelled => ("sftp:transfer_cancelled", "Transfer was cancelled"),
    SftpNotDirectory => ("sftp:not_directory", "Local source is not a directory"),
    SftpUnsupportedFile => ("sftp:unsupported_file", "Special file cannot be transferred"),
    SftpProtectedPath => ("sftp:protected_path", "Protected remote path cannot be deleted"),
    SftpSizeMismatch => ("sftp:size_mismatch", "Transferred file size does not match the expected size"),
    SftpRemoteFileMissing => ("sftp:remote_file_missing", "Remote upload file is missing"),
    SftpTargetIsDirectory => ("sftp:target_is_directory", "Local destination is already a directory"),
    SftpSymlinkUnsupported => ("sftp:symlink_unsupported", "Local symbolic links are not supported on this platform"),
    SftpArchiveUnsupported => ("sftp:archive_unsupported", "Archive format is not supported"),
    SftpArchiveUnsafePath => ("sftp:archive_unsafe_path", "Archive contains an unsafe path"),
    SftpWriteStalled => ("sftp:write_stalled", "SFTP write made no progress before the deadline"),
    SshSystemUnknown => ("ssh:system_unknown", "Remote operating system could not be identified"),
    SshSystemUnsupported => ("ssh:system_unsupported", "Remote operating system is not supported by the monitor"),
    AiActiveProviderChanged => ("ai:active_provider_changed", "Active AI provider differs from the expected selection"),
    AiRevisionConflict => ("ai:revision_conflict", "AI configuration changed; reload before retrying"),
    AiProviderNotFound => ("ai:provider_not_found", "AI provider not found"),
    AiKeyNotFound => ("ai:key_not_found", "AI key does not belong to the specified provider"),
    AiModelNotFound => ("ai:model_not_found", "AI model does not belong to the specified provider"),
    AiProviderLimit => ("ai:provider_limit", "AI provider limit reached"),
    AiKeyLimit => ("ai:key_limit", "AI key limit reached"),
    AiModelLimit => ("ai:model_limit", "AI model limit reached"),
    AiProviderDuplicate => ("ai:provider_duplicate", "AI service endpoint already exists"),
    AiKeyDuplicate => ("ai:key_duplicate", "AI key label already exists in this provider"),
    AiModelDuplicate => ("ai:model_duplicate", "AI model identifier already exists in this provider"),
    AiProviderNameInvalid => ("ai:provider_name_invalid", "AI provider name must contain 1 to 80 characters"),
    AiKeyLabelInvalid => ("ai:key_label_invalid", "AI key label must contain 1 to 80 characters"),
    AiDisplayNameInvalid => ("ai:display_name_invalid", "AI model display name exceeds 80 characters or contains control characters"),
    AiLastKey => ("ai:last_key", "At least one AI key slot must remain"),
    AiLastModel => ("ai:last_model", "At least one AI model must remain"),
    AiReplacementRequired => ("ai:replacement_required", "Select a different replacement from the same AI provider"),
    AiAddressInvalid => ("ai:address_invalid", "Invalid AI service address"),
    AiModelInvalid => ("ai:model_invalid", "AI model name is required or too long"),
    AiConnectionNotConfigured => ("ai:connection_not_configured", "Save the AI service address and model first"),
    AiApiKeyMissing => ("ai:api_key_missing", "No API key is saved yet"),
    AiApiKeyInvalid => ("ai:api_key_invalid", "API key is empty or too long"),
    AiAuthenticationExpired => ("ai:authentication_expired", "AI credential authentication was invalidated by application lifecycle or credential mutation"),
    AiCredentialRollbackFailed => ("ai:credential_rollback_failed", "AI settings were not saved and credential rollback failed"),
    AiStreamRequestIdInvalid => ("ai:stream_request_id_invalid", "Invalid AI stream request id"),
    AiTaskAlreadyRunning => ("ai:task_already_running", "The same AI task is already running"),
    AiRequestTooLarge => ("ai:request_too_large", "AI request exceeds the size limit"),
    AiResponseTooLarge => ("ai:response_too_large", "AI provider response exceeds the size limit"),
    AiOutputTooLarge => ("ai:output_too_large", "AI output exceeds the size limit"),
    AiSchemaTooNew => ("ai:schema_too_new", "AI database schema is newer than this app"),
    AiTranslationRecordInvalid => ("ai:translation_record_invalid", "Stored AI translation is invalid"),
    AiTranslationContentEmpty => ("ai:translation_content_empty", "Translation content is required"),
    AiTranslationContentTooLong => ("ai:translation_content_too_long", "Translation content is too long"),
    AiTranslationNotFound => ("ai:translation_not_found", "AI translation not found"),
    AiTranslationPersistFailed => ("ai:translation_persist_failed", "Failed to persist the AI translation"),
    PoetrySyncBusy => ("poetry:sync_busy", "Another poetry sync is already running"),
    PoetrySyncCancelled => ("poetry:sync_cancelled", "Poetry sync was cancelled"),
    PoetryPoemNotFound => ("poetry:poem_not_found", "Poem not found"),
    PoetryLocalImportUnsupported => ("poetry:local_import_unsupported", "Local poetry import is not available on mobile"),
    PoetryPackImportUnsupported => ("poetry:pack_import_unsupported", "Local translation pack import is not available on mobile"),
    PoetryAnnotationsDesktopOnly => ("poetry:annotations_desktop_only", "Annotation pack downloads require the desktop app"),
    PoetryCatalogInvalid => ("poetry:catalog_invalid", "Poetry collection catalog is invalid"),
    PoetryParseFailed => ("poetry:parse_failed", "Poetry source file could not be parsed"),
    PoetrySourceUnknown => ("poetry:source_unknown", "Unknown poetry source"),
    PoetrySourceMissing => ("poetry:source_missing", "Required poetry source is missing from the catalog"),
    PoetryTreeTruncated => ("poetry:tree_truncated", "Upstream file listing is truncated"),
    PoetryNoMatchingFiles => ("poetry:no_matching_files", "Upstream file listing has no matching files"),
    PoetryUnsafeTreePath => ("poetry:unsafe_tree_path", "Upstream file listing contains an unsafe path"),
    PoetryUnsafeArchivePath => ("poetry:unsafe_archive_path", "Archive contains an unsafe path"),
    PoetryUpstreamResponseInvalid => ("poetry:upstream_response_invalid", "Upstream API response is missing required fields"),
    PoetryApiBudgetTooSmall => ("poetry:api_budget_too_small", "GitHub API request budget is too small for this download"),
    PoetryPackFormatUnsupported => ("poetry:pack_format_unsupported", "Unsupported translation pack format"),
    PoetryPackInvalid => ("poetry:pack_invalid", "Translation pack is invalid"),
    PoetryTranslationSourceEmpty => ("poetry:translation_source_empty", "The poem has no source text to translate"),
    PoetryTranslationInputTooLarge => ("poetry:translation_input_too_large", "The poem is too large for the AI task"),
    PoetryTranslationOutputInvalid => ("poetry:translation_output_invalid", "AI translation output is invalid"),
}
