use crate::error::{AppError, AppResult};
use crate::models::{SftpEntry, SftpFileInfo, TransferProgress};
use base64::{engine::general_purpose::STANDARD, Engine as _};
use parking_lot::{Condvar, Mutex};
use ssh2::{ErrorCode, FileStat, OpenFlags, OpenType, RenameFlags, Session};
use std::collections::{HashMap, HashSet};
use std::env;
use std::fs::{self, OpenOptions};
use std::io::{Read, Seek, SeekFrom, Write};
use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::mpsc::{Receiver, Sender};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tauri::{AppHandle, Emitter};
use walkdir::WalkDir;

const SFTP_KEEPALIVE_INTERVAL_SECS: u32 = 15;
const SFTP_TRANSFER_RETRIES: usize = 10;
const SFTP_TRANSFER_BUFFER_SIZE: usize = 64 * 1024;
const SFTP_TRANSFER_KEEPALIVE_SECS: u64 = 5;
const SFTP_WRITE_STALL_TIMEOUT_SECS: u64 = 5;
const SSH_CONNECT_TIMEOUT_SECS: u64 = 12;
const SSH_OPERATION_TIMEOUT_MS: u32 = 30_000;
const REMOTE_COMMAND_CONFIRM_RETRIES: usize = 60;
const REMOTE_COMMAND_CONFIRM_INTERVAL_MS: u64 = 500;
const LIBSSH2_ERROR_SOCKET_SEND: i32 = -7;
const LIBSSH2_ERROR_TIMEOUT: i32 = -9;
const LIBSSH2_ERROR_SOCKET_DISCONNECT: i32 = -13;
const LIBSSH2_ERROR_SOCKET_TIMEOUT: i32 = -30;
const LIBSSH2_ERROR_SOCKET_RECV: i32 = -43;
const LIBSSH2_ERROR_BAD_SOCKET: i32 = -45;

include!("ssh/types.rs");
include!("ssh/auth.rs");
include!("ssh/transfer_models.rs");
include!("ssh/archive.rs");
include!("ssh/manager_session.rs");
include!("ssh/transfer_control.rs");
include!("ssh/temp_cleanup.rs");
include!("ssh/transfer_io.rs");
include!("ssh/sftp_basic.rs");
include!("ssh/remote_ops.rs");
include!("ssh/upload.rs");
include!("ssh/download_file.rs");
include!("ssh/download_archive.rs");
include!("ssh/download_direct.rs");
include!("ssh/extract.rs");
include!("ssh/path_utils.rs");
include!("ssh/shell_worker.rs");
