// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	hostsList: () => typedError<Host[], AppError>(__TAURI_INVOKE("hosts_list")),
	hostGet: (id: string) => typedError<Host, AppError>(__TAURI_INVOKE("host_get", { id })),
	hostCreate: (input: HostInput) => typedError<Host, AppError>(__TAURI_INVOKE("host_create", { input })),
	hostUpdate: (id: string, input: HostInput) => typedError<Host, AppError>(__TAURI_INVOKE("host_update", { id, input })),
	hostDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("host_delete", { id })),
	hostsReorder: (orderedIds: string[]) => typedError<Host[], AppError>(__TAURI_INVOKE("hosts_reorder", { orderedIds })),
	keysList: () => typedError<SshKey[], AppError>(__TAURI_INVOKE("keys_list")),
	keyImport: (label: string, sourcePath: string, hasPassphrase: boolean) => typedError<SshKey, AppError>(__TAURI_INVOKE("key_import", { label, sourcePath, hasPassphrase })),
	keyDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("key_delete", { id })),
	lanTransferSettings: () => typedError<LanTransferSettings, AppError>(__TAURI_INVOKE("lan_transfer_settings")),
	lanTransferSaveSettings: (settings: LanTransferSettings) => typedError<LanTransferSettings, AppError>(__TAURI_INVOKE("lan_transfer_save_settings", { settings })),
	lanTransferStatus: () => typedError<LanTransferStatus, AppError>(__TAURI_INVOKE("lan_transfer_status")),
	lanTransferNetworkAddresses: () => typedError<LanNetworkAddress[], AppError>(__TAURI_INVOKE("lan_transfer_network_addresses")),
	lanTransferDiscoverDevices: () => typedError<LanDiscoveredDevice[], AppError>(__TAURI_INVOKE("lan_transfer_discover_devices")),
	lanTransferConnectedDevices: () => typedError<LanConnectedDevice[], AppError>(__TAURI_INVOKE("lan_transfer_connected_devices")),
	lanTransferPendingAuthRequests: () => typedError<LanAuthRequest[], AppError>(__TAURI_INVOKE("lan_transfer_pending_auth_requests")),
	lanTransferApproveAuthRequest: (id: string, permission: string) => typedError<boolean, AppError>(__TAURI_INVOKE("lan_transfer_approve_auth_request", { id, permission })),
	lanTransferRejectAuthRequest: (id: string) => typedError<boolean, AppError>(__TAURI_INVOKE("lan_transfer_reject_auth_request", { id })),
	lanTransferDisconnectDevice: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("lan_transfer_disconnect_device", { id })),
	lanTransferTasks: () => typedError<LanTransferTask[], AppError>(__TAURI_INVOKE("lan_transfer_tasks")),
	lanTransferCancelTask: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("lan_transfer_cancel_task", { id })),
	lanTransferStart: () => typedError<LanTransferStatus, AppError>(__TAURI_INVOKE("lan_transfer_start")),
	lanTransferStop: () => typedError<LanTransferStatus, AppError>(__TAURI_INVOKE("lan_transfer_stop")),
	lanTransferSharedDirs: () => typedError<LanSharedDir[], AppError>(__TAURI_INVOKE("lan_transfer_shared_dirs")),
	lanTransferAddSharedDir: (input: LanSharedDirInput) => typedError<LanSharedDir, AppError>(__TAURI_INVOKE("lan_transfer_add_shared_dir", { input })),
	lanTransferDeleteSharedDir: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("lan_transfer_delete_shared_dir", { id })),
	lanTransferTrustedDevices: () => typedError<LanTrustedDevice[], AppError>(__TAURI_INVOKE("lan_transfer_trusted_devices")),
	lanTransferAddTrustedDevice: (input: LanTrustedDeviceInput) => typedError<LanTrustedDevice, AppError>(__TAURI_INVOKE("lan_transfer_add_trusted_device", { input })),
	lanTransferDeleteTrustedDevice: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("lan_transfer_delete_trusted_device", { id })),
	activityLogs: (limit: number | null) => typedError<ActivityLog[], AppError>(__TAURI_INVOKE("activity_logs", { limit })),
	activityLogsClear: () => typedError<null, AppError>(__TAURI_INVOKE("activity_logs_clear")),
	activityLogDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("activity_log_delete", { id })),
	sshConnect: (hostId: string, passphrase: string | null) => typedError<string, AppError>(__TAURI_INVOKE("ssh_connect", { hostId, passphrase })),
	sshOpenShell: (sessionId: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("ssh_open_shell", { sessionId, cols, rows })),
	sshWrite: (sessionId: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("ssh_write", { sessionId, data })),
	sshResize: (sessionId: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("ssh_resize", { sessionId, cols, rows })),
	sshDisconnect: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("ssh_disconnect", { sessionId })),
	sftpHome: (sessionId: string) => typedError<string, AppError>(__TAURI_INVOKE("sftp_home", { sessionId })),
	sftpStartDir: (sessionId: string, preferred: string | null) => typedError<string, AppError>(__TAURI_INVOKE("sftp_start_dir", { sessionId, preferred })),
	sftpList: (sessionId: string, path: string) => typedError<SftpEntry[], AppError>(__TAURI_INVOKE("sftp_list", { sessionId, path })),
	sftpInfo: (sessionId: string, path: string) => typedError<SftpFileInfo, AppError>(__TAURI_INVOKE("sftp_info", { sessionId, path })),
	sftpMkdir: (sessionId: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("sftp_mkdir", { sessionId, path })),
	sftpRename: (sessionId: string, from: string, to: string) => typedError<null, AppError>(__TAURI_INVOKE("sftp_rename", { sessionId, from, to })),
	sftpDelete: (sessionId: string, path: string, isDir: boolean, transferId: string | null) => typedError<null, AppError>(__TAURI_INVOKE("sftp_delete", { sessionId, path, isDir, transferId })),
	sftpDownload: (sessionId: string, remote: string, local: string, transferId: string | null) => typedError<null, AppError>(__TAURI_INVOKE("sftp_download", { sessionId, remote, local, transferId })),
	sftpUpload: (sessionId: string, local: string, remote: string, transferId: string | null) => typedError<null, AppError>(__TAURI_INVOKE("sftp_upload", { sessionId, local, remote, transferId })),
	sftpExists: (sessionId: string, path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("sftp_exists", { sessionId, path })),
	sftpUploadDir: (sessionId: string, localDir: string, remoteParent: string, remoteName: string, transferMode: string | null, transferId: string | null) => typedError<null, AppError>(__TAURI_INVOKE("sftp_upload_dir", { sessionId, localDir, remoteParent, remoteName, transferMode, transferId })),
	sftpDownloadDir: (sessionId: string, remoteDir: string, localDir: string, transferMode: string | null, transferId: string | null) => typedError<null, AppError>(__TAURI_INVOKE("sftp_download_dir", { sessionId, remoteDir, localDir, transferMode, transferId })),
	sftpCancelTransfer: (transferId: string) => typedError<null, AppError>(__TAURI_INVOKE("sftp_cancel_transfer", { transferId })),
	sftpPauseTransfer: (transferId: string) => typedError<null, AppError>(__TAURI_INVOKE("sftp_pause_transfer", { transferId })),
	sftpResumeTransfer: (transferId: string) => typedError<null, AppError>(__TAURI_INVOKE("sftp_resume_transfer", { transferId })),
	sftpResetConnection: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("sftp_reset_connection", { sessionId })),
	sftpExtract: (sessionId: string, remoteArchive: string, remoteParent: string, outName: string | null) => typedError<null, AppError>(__TAURI_INVOKE("sftp_extract", { sessionId, remoteArchive, remoteParent, outName })),
	gameRoomStatus: () => typedError<GameRoomStatus, AppError>(__TAURI_INVOKE("game_room_status")),
	gameRoomCreate: (gameId: string, roomName: string, code: string | null, playerName: string) => typedError<GameRoomStatus, AppError>(__TAURI_INVOKE("game_room_create", { gameId, roomName, code, playerName })),
	gameRoomJoin: (host: string, port: number, gameId: string, code: string | null, playerName: string) => typedError<GameRoomStatus, AppError>(__TAURI_INVOKE("game_room_join", { host, port, gameId, code, playerName })),
	gameRoomDiscover: (gameId: string) => typedError<GameRoomSummary[], AppError>(__TAURI_INVOKE("game_room_discover", { gameId })),
	gameRoomSend: (payload: string) => typedError<null, AppError>(__TAURI_INVOKE("game_room_send", { payload })),
	gameRoomLeave: () => typedError<null, AppError>(__TAURI_INVOKE("game_room_leave")),
	vaultEntriesList: () => typedError<VaultEntry[], AppError>(__TAURI_INVOKE("vault_entries_list")),
	vaultEntryCreate: (input: VaultEntryInput) => typedError<VaultEntry, AppError>(__TAURI_INVOKE("vault_entry_create", { input })),
	vaultEntryUpdate: (id: string, input: VaultEntryInput) => typedError<VaultEntry, AppError>(__TAURI_INVOKE("vault_entry_update", { id, input })),
	vaultEntryDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("vault_entry_delete", { id })),
	/**
	 *  Serialize the selected sections as a JSON document, optionally encrypted
	 *  with a password (Argon2id + ChaCha20-Poly1305). The frontend handles the
	 *  save dialog / file write so browser dev mode works too.
	 */
	dataExport: (sections: ExportSection[], password: string | null) => typedError<string, AppError>(__TAURI_INVOKE("data_export", { sections, password })),
	// Detect whether a file is an mftp export and whether it is encrypted.
	dataInspect: (raw: string) => typedError<ImportPreview, AppError>(__TAURI_INVOKE("data_inspect", { raw })),
	dataImport: (raw: string, password: string | null, mode: ImportMode) => typedError<ImportReport, AppError>(__TAURI_INVOKE("data_import", { raw, password, mode })),
};

/* Types */
export type ActivityLog = {
	id: string,
	createdAt: number,
	source: string,
	ip: string,
	requestType: string,
	result: string,
	detail?: string | null,
};

// Unified error type surfaced to the frontend as a plain string.
export type AppError = string;

export type AuthType = "password" | "key";

// A data section that can be exported; add a variant per exportable module.
export type ExportSection = "vault" | "hosts";

export type GameRoomStatus = {
	// "idle" | "hosting" | "joined"
	phase: string,
	roomId: string | null,
	gameId: string | null,
	roomName: string | null,
	host: string | null,
	port: number | null,
	// 0 = host (first seat), 1 = guest.
	seat: number | null,
	playerName: string | null,
	peerName: string | null,
	hasCode: boolean,
	// Only present for the host, so the UI can show the code to share.
	code: string | null,
};

export type GameRoomSummary = {
	roomId: string,
	gameId: string,
	roomName: string,
	hostName: string,
	ip: string,
	port: number,
	hasCode: boolean,
};

export type Host = {
	id: string,
	label: string,
	host: string,
	port: number,
	username: string,
	authType: AuthType,
	password?: string | null,
	keyId?: string | null,
	// Directory to open first in SFTP; falls back to home then "/" if missing.
	defaultPath?: string | null,
	createdAt: number,
	updatedAt: number,
};

// Payload for creating/updating a host (id/timestamps managed by backend).
export type HostInput = {
	label: string,
	host: string,
	port: number,
	username: string,
	authType: AuthType,
	password?: string | null,
	keyId?: string | null,
	defaultPath?: string | null,
};

// How imported records are applied to existing data.
export type ImportMode = 
// Clear the section first, then insert everything from the file.
"overwrite" | 
// Update records with matching ids, insert the rest.
"merge" | 
// Insert everything as new records with fresh ids.
"append";

export type ImportPreview = {
	encrypted: boolean,
	// Empty for encrypted files until they are decrypted during import.
	sections: ExportSection[],
};

export type ImportReport = {
	sections: ImportSectionReport[],
};

export type ImportSectionReport = {
	section: ExportSection,
	inserted: number,
	updated: number,
};

export type LanAuthRequest = {
	id: string,
	ip: string,
	deviceName: string,
	accessType: string,
	requestedAt: number,
};

export type LanConnectedDevice = {
	id: string,
	ip: string,
	deviceName: string,
	permission: string,
	connectedAt: number,
	lastSeen: number,
	currentOperation: string,
};

export type LanDiscoveredDevice = {
	id: string,
	deviceName: string,
	ip: string,
	port: number,
	url: string,
	online: boolean,
	lastSeen: number,
};

export type LanNetworkAddress = {
	interfaceName: string,
	ip: string,
	recommended: boolean,
};

export type LanSharedDir = {
	id: string,
	name: string,
	path: string,
	createdAt: number,
};

export type LanSharedDirInput = {
	name: string,
	path: string,
};

export type LanTransferSettings = {
	deviceName: string,
	port: number,
	bindHost: string,
	downloadDir: string,
	autoStart: boolean,
	securityMode: string,
	defaultPermission: string,
	maxConcurrentTransfers: number,
};

export type LanTransferStatus = {
	running: boolean,
	host: string | null,
	port: number | null,
	url: string | null,
	onlineConnections: number,
	authMode: string,
	confirmationCode?: string | null,
};

export type LanTransferTask = {
	id: string,
	direction: string,
	fileName: string,
	ip: string,
	status: string,
	transferred: number,
	total: number,
	startedAt: number,
	updatedAt: number,
};

export type LanTrustedDevice = {
	id: string,
	label: string,
	ip: string,
	createdAt: number,
};

export type LanTrustedDeviceInput = {
	label: string,
	ip: string,
};

// A remote directory entry returned by SFTP listing.
export type SftpEntry = {
	name: string,
	path: string,
	isDir: boolean,
	isSymlink: boolean,
	size: number,
	mtime: number,
	mode: number,
};

export type SftpFileInfo = {
	name: string,
	path: string,
	isDir: boolean,
	isSymlink: boolean,
	size: number,
	atime: number,
	mtime: number,
	createdAt?: number | null,
	mode: number,
	uid?: number | null,
	gid?: number | null,
};

export type SshKey = {
	id: string,
	label: string,
	filename: string,
	hasPassphrase: boolean,
	createdAt: number,
};

export type TransferProgress = {
	id: string,
	phase: string,
	transferred: number,
	total: number | null,
};

export type VaultEntry = {
	id: string,
	title: string,
	url?: string | null,
	username?: string | null,
	password?: string | null,
	category?: string | null,
	notes?: string | null,
	createdAt: number,
	updatedAt: number,
};

// Payload for creating/updating a vault entry (id/timestamps managed by backend).
export type VaultEntryInput = {
	title: string,
	url?: string | null,
	username?: string | null,
	password?: string | null,
	category?: string | null,
	notes?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

