/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GamesBilliardsRouteImport } from './routes/games/billiards'
import { Route as GamesGoRouteImport } from './routes/games/go'
import { Route as GamesGomokuRouteImport } from './routes/games/gomoku'
import { Route as GamesXiangqiRouteImport } from './routes/games/xiangqi'
import { Route as ToolsCryptoRouteImport } from './routes/tools/crypto'
import { Route as ToolsFormatterRouteImport } from './routes/tools/formatter'
import { Route as ToolsImageCompressRouteImport } from './routes/tools/image-compress'
import { Route as ToolsLanTransferRouteImport } from './routes/tools/lan-transfer'
import { Route as ToolsMediaCompressRouteImport } from './routes/tools/media-compress'
import { Route as ToolsSshSftpRouteImport } from './routes/tools/ssh-sftp'
import { Route as ToolsVideoCompressRouteImport } from './routes/tools/video-compress'
import { Route as ToolsWebBrowserRouteImport } from './routes/tools/web-browser'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesBilliardsRoute = GamesBilliardsRouteImport.update({
  id: '/games/billiards',
  path: '/games/billiards',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGoRoute = GamesGoRouteImport.update({
  id: '/games/go',
  path: '/games/go',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGomokuRoute = GamesGomokuRouteImport.update({
  id: '/games/gomoku',
  path: '/games/gomoku',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesXiangqiRoute = GamesXiangqiRouteImport.update({
  id: '/games/xiangqi',
  path: '/games/xiangqi',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCryptoRoute = ToolsCryptoRouteImport.update({
  id: '/tools/crypto',
  path: '/tools/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFormatterRoute = ToolsFormatterRouteImport.update({
  id: '/tools/formatter',
  path: '/tools/formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressRoute = ToolsImageCompressRouteImport.update({
  id: '/tools/image-compress',
  path: '/tools/image-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLanTransferRoute = ToolsLanTransferRouteImport.update({
  id: '/tools/lan-transfer',
  path: '/tools/lan-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMediaCompressRoute = ToolsMediaCompressRouteImport.update({
  id: '/tools/media-compress',
  path: '/tools/media-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSshSftpRoute = ToolsSshSftpRouteImport.update({
  id: '/tools/ssh-sftp',
  path: '/tools/ssh-sftp',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVideoCompressRoute = ToolsVideoCompressRouteImport.update({
  id: '/tools/video-compress',
  path: '/tools/video-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWebBrowserRoute = ToolsWebBrowserRouteImport.update({
  id: '/tools/web-browser',
  path: '/tools/web-browser',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/games/billiards': typeof GamesBilliardsRoute
  '/games/go': typeof GamesGoRoute
  '/games/gomoku': typeof GamesGomokuRoute
  '/games/xiangqi': typeof GamesXiangqiRoute
  '/tools/crypto': typeof ToolsCryptoRoute
  '/tools/formatter': typeof ToolsFormatterRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/lan-transfer': typeof ToolsLanTransferRoute
  '/tools/media-compress': typeof ToolsMediaCompressRoute
  '/tools/ssh-sftp': typeof ToolsSshSftpRoute
  '/tools/video-compress': typeof ToolsVideoCompressRoute
  '/tools/web-browser': typeof ToolsWebBrowserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/games/billiards': typeof GamesBilliardsRoute
  '/games/go': typeof GamesGoRoute
  '/games/gomoku': typeof GamesGomokuRoute
  '/games/xiangqi': typeof GamesXiangqiRoute
  '/tools/crypto': typeof ToolsCryptoRoute
  '/tools/formatter': typeof ToolsFormatterRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/lan-transfer': typeof ToolsLanTransferRoute
  '/tools/media-compress': typeof ToolsMediaCompressRoute
  '/tools/ssh-sftp': typeof ToolsSshSftpRoute
  '/tools/video-compress': typeof ToolsVideoCompressRoute
  '/tools/web-browser': typeof ToolsWebBrowserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/games/billiards': typeof GamesBilliardsRoute
  '/games/go': typeof GamesGoRoute
  '/games/gomoku': typeof GamesGomokuRoute
  '/games/xiangqi': typeof GamesXiangqiRoute
  '/tools/crypto': typeof ToolsCryptoRoute
  '/tools/formatter': typeof ToolsFormatterRoute
  '/tools/image-compress': typeof ToolsImageCompressRoute
  '/tools/lan-transfer': typeof ToolsLanTransferRoute
  '/tools/media-compress': typeof ToolsMediaCompressRoute
  '/tools/ssh-sftp': typeof ToolsSshSftpRoute
  '/tools/video-compress': typeof ToolsVideoCompressRoute
  '/tools/web-browser': typeof ToolsWebBrowserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/games/billiards'
    | '/games/go'
    | '/games/gomoku'
    | '/games/xiangqi'
    | '/tools/crypto'
    | '/tools/formatter'
    | '/tools/image-compress'
    | '/tools/lan-transfer'
    | '/tools/media-compress'
    | '/tools/ssh-sftp'
    | '/tools/video-compress'
    | '/tools/web-browser'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/games/billiards'
    | '/games/go'
    | '/games/gomoku'
    | '/games/xiangqi'
    | '/tools/crypto'
    | '/tools/formatter'
    | '/tools/image-compress'
    | '/tools/lan-transfer'
    | '/tools/media-compress'
    | '/tools/ssh-sftp'
    | '/tools/video-compress'
    | '/tools/web-browser'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/games/billiards'
    | '/games/go'
    | '/games/gomoku'
    | '/games/xiangqi'
    | '/tools/crypto'
    | '/tools/formatter'
    | '/tools/image-compress'
    | '/tools/lan-transfer'
    | '/tools/media-compress'
    | '/tools/ssh-sftp'
    | '/tools/video-compress'
    | '/tools/web-browser'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  GamesBilliardsRoute: typeof GamesBilliardsRoute
  GamesGoRoute: typeof GamesGoRoute
  GamesGomokuRoute: typeof GamesGomokuRoute
  GamesXiangqiRoute: typeof GamesXiangqiRoute
  ToolsCryptoRoute: typeof ToolsCryptoRoute
  ToolsFormatterRoute: typeof ToolsFormatterRoute
  ToolsImageCompressRoute: typeof ToolsImageCompressRoute
  ToolsLanTransferRoute: typeof ToolsLanTransferRoute
  ToolsMediaCompressRoute: typeof ToolsMediaCompressRoute
  ToolsSshSftpRoute: typeof ToolsSshSftpRoute
  ToolsVideoCompressRoute: typeof ToolsVideoCompressRoute
  ToolsWebBrowserRoute: typeof ToolsWebBrowserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/billiards': {
      id: '/games/billiards'
      path: '/games/billiards'
      fullPath: '/games/billiards'
      preLoaderRoute: typeof GamesBilliardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/go': {
      id: '/games/go'
      path: '/games/go'
      fullPath: '/games/go'
      preLoaderRoute: typeof GamesGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/gomoku': {
      id: '/games/gomoku'
      path: '/games/gomoku'
      fullPath: '/games/gomoku'
      preLoaderRoute: typeof GamesGomokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/xiangqi': {
      id: '/games/xiangqi'
      path: '/games/xiangqi'
      fullPath: '/games/xiangqi'
      preLoaderRoute: typeof GamesXiangqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/crypto': {
      id: '/tools/crypto'
      path: '/tools/crypto'
      fullPath: '/tools/crypto'
      preLoaderRoute: typeof ToolsCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/formatter': {
      id: '/tools/formatter'
      path: '/tools/formatter'
      fullPath: '/tools/formatter'
      preLoaderRoute: typeof ToolsFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compress': {
      id: '/tools/image-compress'
      path: '/tools/image-compress'
      fullPath: '/tools/image-compress'
      preLoaderRoute: typeof ToolsImageCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/lan-transfer': {
      id: '/tools/lan-transfer'
      path: '/tools/lan-transfer'
      fullPath: '/tools/lan-transfer'
      preLoaderRoute: typeof ToolsLanTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/media-compress': {
      id: '/tools/media-compress'
      path: '/tools/media-compress'
      fullPath: '/tools/media-compress'
      preLoaderRoute: typeof ToolsMediaCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ssh-sftp': {
      id: '/tools/ssh-sftp'
      path: '/tools/ssh-sftp'
      fullPath: '/tools/ssh-sftp'
      preLoaderRoute: typeof ToolsSshSftpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/video-compress': {
      id: '/tools/video-compress'
      path: '/tools/video-compress'
      fullPath: '/tools/video-compress'
      preLoaderRoute: typeof ToolsVideoCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/web-browser': {
      id: '/tools/web-browser'
      path: '/tools/web-browser'
      fullPath: '/tools/web-browser'
      preLoaderRoute: typeof ToolsWebBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  GamesBilliardsRoute: GamesBilliardsRoute,
  GamesGoRoute: GamesGoRoute,
  GamesGomokuRoute: GamesGomokuRoute,
  GamesXiangqiRoute: GamesXiangqiRoute,
  ToolsCryptoRoute: ToolsCryptoRoute,
  ToolsFormatterRoute: ToolsFormatterRoute,
  ToolsImageCompressRoute: ToolsImageCompressRoute,
  ToolsLanTransferRoute: ToolsLanTransferRoute,
  ToolsMediaCompressRoute: ToolsMediaCompressRoute,
  ToolsSshSftpRoute: ToolsSshSftpRoute,
  ToolsVideoCompressRoute: ToolsVideoCompressRoute,
  ToolsWebBrowserRoute: ToolsWebBrowserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
