/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSshSftpRouteImport } from './routes/tools/ssh-sftp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSshSftpRoute = ToolsSshSftpRouteImport.update({
  id: '/tools/ssh-sftp',
  path: '/tools/ssh-sftp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/ssh-sftp': typeof ToolsSshSftpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/ssh-sftp': typeof ToolsSshSftpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/ssh-sftp': typeof ToolsSshSftpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/ssh-sftp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/ssh-sftp'
  id: '__root__' | '/' | '/tools/ssh-sftp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsSshSftpRoute: typeof ToolsSshSftpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ssh-sftp': {
      id: '/tools/ssh-sftp'
      path: '/tools/ssh-sftp'
      fullPath: '/tools/ssh-sftp'
      preLoaderRoute: typeof ToolsSshSftpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsSshSftpRoute: ToolsSshSftpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
