import type { AppError } from "~/bindings";

export type {
  ActivityLog,
  AppDataClearResult,
  AppDataModule,
  AppDataUsage,
  AppError,
  AuthType,
  AuthorBio,
  AuthorSummary,
  BtControlAction,
  BtFileMeta,
  BtPeerInfo,
  BtProbeResult,
  BtTaskEvent,
  BtTaskInfo,
  BtTaskState,
  ExportSection,
  ImportMode,
  ImportPreview,
  ImportReport,
  GameRoomStatus,
  GameRoomSummary,
  Host,
  HostInput,
  LanAuthRequest,
  LanConnectedDevice,
  LanDiscoveredDevice,
  LanNetworkAddress,
  LanSharedDir,
  LanSharedDirInput,
  LanTransferSettings,
  LanTransferStatus,
  LanTransferTask,
  LanTrustedDevice,
  LanTrustedDeviceInput,
  PoemAnnotation,
  PoemDetail,
  PoemPage,
  PoemSummary,
  PoetryAnnotationsStatus,
  PoetryAuthorsRequest,
  PoetryBrowseRequest,
  PoetryCollectionStatus,
  PoetryContentIndexStatus,
  PoetryScript,
  PoetrySearchRequest,
  PoetrySearchResult,
  PoetrySearchScope,
  PoetrySourceStatus,
  PoetrySyncPlan,
  PoetrySyncProgress,
  PoetryTier,
  SftpEntry,
  SftpFileInfo,
  SshKey,
  SystemCpu,
  SystemDisk,
  SystemDiskIoRate,
  SystemLoad,
  SystemMemory,
  SystemNetworkRate,
  SystemProcess,
  SystemStats,
  TodoItem,
  TodoItemInput,
  TransferProgress,
  VaultEntry,
  VaultEntryInput,
} from "~/bindings";

/** An open terminal/sftp/sysmon session tab. */
export interface Session {
  id: string;
  hostId: string;
  title: string;
  status: "connecting" | "connected" | "closed" | "error";
  /** 统一的四字段错误；渲染时再本地化，不保存字符串文案。 */
  error?: AppError;
  view: "terminal" | "sftp" | "monitor";
}
